# Generated by Django 3.2.5 on 2021-09-03 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210903_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publish_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Publish'), ('DR', 'Draft')], default=datetime.datetime(2021, 9, 3, 16, 0, 31, 709326, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
