# Generated by Django 3.2.5 on 2021-07-24 09:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210722_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 24, 9, 16, 25, 732355, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
