version: "3.8"
   
services:

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/netflix_demo
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=netflixdemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=netflixdemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
